import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cart = cookies().get("cart")?.value || "{}";
  const parsedCart: Record<string, number> = JSON.parse(cart);

  const cartCount = Object.values(parsedCart).reduce(
    (total, quantity) => total + quantity,
    0
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-8 text-blue-800 underline">
          <Link href="/">Home</Link>
          <Link href="/cart">Cart ({cartCount})</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
